
import { PaymentMethod, PaymentStatus } from '../types';

interface PaymentResult {
    success: boolean;
    transactionId?: string;
    message?: string;
    pixCode?: string;
}

export const PaymentService = {
    // Simulate processing time
    processPayment: async (
        amount: number,
        method: PaymentMethod,
        cardData?: any
    ): Promise<PaymentResult> => {
        return new Promise((resolve) => {
            setTimeout(() => {
                // Mock Success Logic
                // In a real app, this would call Stripe/Pagar.me/MercadoPago

                if (method === 'credit_card') {
                    // Simple mock validation
                    if (!cardData || !cardData.number || cardData.number.length < 16) {
                        resolve({ success: false, message: 'Dados do cartão inválidos.' });
                        return;
                    }
                }

                resolve({
                    success: true,
                    transactionId: `TX-${Math.floor(Math.random() * 1000000)}`,
                    message: 'Pagamento aprovado com sucesso!'
                });
            }, 2000);
        });
    },

    generatePixCode: (amount: number, transactionId: string): string => {
        // Returns a static PIX copy-paste code for demo
        // In production, this would be generated by the Payment Gateway API
        return `00020126580014BR.GOV.BCB.PIX0136123e4567-e89b-12d3-a456-426614174000520400005303986540${amount.toFixed(2).replace('.', '')}5802BR5913NaturaVida App6008Brasilia62070503***6304${transactionId}`;
    }
};
